// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SvxlinkManagerV2.Infrastructure.Persistence;

#nullable disable

namespace SvxlinkManagerV2.Infrastructure.Migrations
{
    [DbContext(typeof(SvxlinkDbContext))]
    partial class SvxlinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SvxlinkManagerV2.Domain.Aggregates.GeneralConfiguration.GeneralConfigurationAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultRxFrequency")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultTxFrequency")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StartDefaultSalonOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartReflectorOnStartup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GeneralConfigurations");
                });

            modelBuilder.Entity("SvxlinkManagerV2.Domain.Aggregates.Reflector.ReflectorAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reflectors");
                });

            modelBuilder.Entity("SvxlinkManagerV2.Domain.Aggregates.SA818.SA818Aggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Bandwidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HighPass")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LowPass")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreEmph")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Squelch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SA818");
                });

            modelBuilder.Entity("SvxlinkManagerV2.Domain.Aggregates.Salon.SalonAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DtmfCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salons");
                });

            modelBuilder.Entity("SvxlinkManagerV2.Domain.Aggregates.Salon.SalonAggregate", b =>
                {
                    b.OwnsOne("SvxlinkManagerV2.Domain.Aggregates.Salon.Entities.SvxLinkConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("SalonAggregateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuthKey")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Callsign")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("CardChannels")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CardSampleRate")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CertEmail")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CfgDir")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DefaultLang")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("DefaultTg")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<int>("JitterBufferDelay")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Logics")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("LongIdentInterval")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Modules")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("MonitorTgs")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("MuteFirstTxLoc")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("MuteFirstTxRem")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Port")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("QsyPendingTimeout")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ReflectorProtocol")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ReportCtcss")
                                .HasColumnType("TEXT");

                            b1.Property<int>("RgrSoundDelay")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("RxCtcss")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("RxFrequency")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ShortIdentInterval")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("SimplexCallsign")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("TgSelectInhibitTimeout")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TgSelectTimeout")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TmpMonitorTimeout")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("TxCtcss")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("TxFrequency")
                                .HasColumnType("TEXT");

                            b1.HasKey("SalonAggregateId");

                            b1.ToTable("Salons");

                            b1.ToJson("Configuration");

                            b1.WithOwner()
                                .HasForeignKey("SalonAggregateId");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
