[GLOBAL]
TIMESTAMP_FORMAT="%c"
LISTEN_PORT=5300
ACCEPT_CALLSIGN=.*
CODECS=OPUS
CERT_PKI_DIR=/var/lib/svxlink/pki
TG_FOR_V1_CLIENTS=0

[ROOT_CA]
COMMON_NAME=SvxReflector Root CA
COUNTRY=CH

[ISSUING_CA]
COMMON_NAME=SvxReflector Issuing CA
COUNTRY=CH

[SERVER_CERT]
COMMON_NAME=svxreflector
SUBJECT_ALT_NAME=DNS:localhost,IP:127.0.0.1

[TG#0]
AUTO_QSY_AFTER=0
ALLOW=.*
SHOW_ACTIVITY=1

[USERS]
# Clients V2 (AUTH_KEY) — Exemple : CALLSIGN=GroupeMotDePasse
# F5ZZZ-L=Noeuds

[PASSWORDS]
# Mots de passe V2 — Exemple : GroupeMotDePasse="MotDePasse"
# Noeuds="Passw0rd"